name: ssl-update

on:
  schedule:
    - cron: '00 12 1 * *'
  workflow_dispatch:

jobs:
  build:
    name: Update
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: 22
          script: |
            sudo certbot renew --post-hook "nginx -s reload"
